const SPECIALITY = {
  BACKEND: "BACKEND",
  FRONTEND: "FRONTEND",
  FULLSTACK: "FULLSTACK",
  MOBILE: "MOBILE",
  DATA_SCIENCE: "DATA_SCIENCE",
  DEVOPS: "DEVOPS",
  UI_UX_DESIGN: "UI_UX_DESIGN",
} as const;

export type SPECIALITY = (typeof SPECIALITY)[keyof typeof SPECIALITY];
export { SPECIALITY };
